import { text, date, integer, timestamp } from "drizzle-orm/pg-core";
import { updateReasonEnum } from "./enums.js";

/** Columns shared by statutes_current and statutes_history */
export function statuteContentColumns() {
  return {
    /** = Vaquill's display_path */
    titlePath: text(),
    text: text().notNull(),

    /** Generated in project, no hash provided by Vaquill */
    sourceHash: text().notNull(),

    /** Date statute went into effect, only populated once a tracked bill amends the statute and an actual enactment date is observed — Vaquill has no value for this */
    effectiveDate: date(),
    /** Not an effective date — a plain year, often null */
    lastAmendedYear: integer(),
    sourceUrl: text(),
    wordCount: integer(),
    subsectionCount: integer(),
    /** Status from Vaquill's `act_status`, not trustworthy as most are just "in_force" */
    sourceStatus: text(),

    /** App-validated tags for genuine ingestion-time judgments (e.g. status_text_mismatch, low_confidence_extraction) */
    dataQualityFlags: text().array(),
    /** = Vaquill's public_laws_referenced. Provenance, not a relationship — doesn't point at an ingested row. */
    enactedByPublicLaws: text().array(),

    /** Why *this* version was written @see {@link updateReasonEnum} */
    updateReason: updateReasonEnum().notNull(),

    /** The ELI5 summary generated by an LLM, null until generation completes — response is never blocked on it */
    summary: text(),
    summaryModelUsed: text(),
    summaryGeneratedAt: timestamp(),
  };
}
